/*  -- +===================================================================+
  -- +                           urbanefficiency
  -- +===================================================================+
  -- |                                                                    |
  -- |Author: Kullayappa Adapala                                          |
  -- |Initial Build Date:  6/12/2020                                      |
  -- |Source File Name: SBQQ_recommendation_Helper.apxc                   |
     |                                                                    |
  -- |                                                                    |
  -- |                                                                    |
  -- |Usage: using the recursive trigger                                  |
  -- |                                                                    |
  -- |Modification History:                                               |
  -- |=====================                                               |
  -- |Version     Date           Author       Remarks                     |
  -- |=========   ============  =========    ===========================  |
  -- |1.0          6/12/2020   Kullayappa A    Initial draft version      |
  -- +===================================================================+
  */
Public class SBQQ_recommendation_Helper{
    Public Static boolean WrkOrderline=true;
}